name: scrna-analysis
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - python=3.9
  # Core Scientific Computing
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  
  # Machine Learning
  - scikit-learn>=1.0.0
  
  # Visualization
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # Single-Cell Analysis
  - scanpy>=1.9.0
  - anndata>=0.8.0
  - leidenalg>=0.8.0
  - python-igraph>=0.9.0
  
  # Deep Learning (CPU version - modify for GPU if needed)
  - pytorch>=1.12.0
  - pytorch-lightning>=1.7.0
  
  # Development tools
  - jupyter
  - ipykernel
  
  # For GPU support, replace pytorch line above with:
  # - pytorch-cuda=11.8
  # - pytorch>=1.12.0